spring:
  cloud:
    gateway:
      routes:
        - id: micro-productos
          uri: lb://micro-productos
          predicates:
            - Path=/v1/productos/**
          filters:
            - StripPrefix=2
            - ExampleCookie=Este es un mensaje personalizado para filter factory, usuario, IsaiasMorochi
        - id: micro-items
          uri: lb://micro-items
          predicates:
            - Path=/v1/items/**
          filters:
            - StripPrefix=2
            - AddResponseHeader=token-response, 12345678
            - SetResponseHeader=Content-Type, application/json;charset=UTF-8
            - AddRequestHeader=token-request, 123456
            - AddRequestarameter=name, isaias
        - id: micro-usuarios
          uri: lb://micro-usuarios
          predicates:
            - Path=/v1/usuarios/**
          filters:
            - StripPrefix=2
        - id: micro-oauth
          uri: lb://micro-oauth
          predicates:
            - Path=/v1/security/**
          filters:
            - StripPrefix=2